#!/usr/bin/env node
'use strict';
/**
 * Prometheus scrape configuration from the host inventory (roadmap Track O): one job per service
 * with a port, scraping its loopback /metrics, plus the extra targets a service declares:
 *
 *   "tools": { …, "metrics": { "extra": [{ "name": "img", "port": 4012 }, …] } }   more processes
 *   "sites": { …, "metrics": false }                                              nothing to scrape
 *
 * Every target is 127.0.0.1 (the services answer /metrics only to direct loopback callers), and
 * node-exporter (host CPU, memory, disk) is scraped on 127.0.0.1:9100.
 *
 *   node scripts/prometheus-config.js [--inventory /etc/openvibe/host.json] [--interval 30s] > prometheus.yml
 */
const fs = require('fs');

function arg(name, fallback) {
    const i = process.argv.indexOf(`--${name}`);
    return i > 0 && process.argv[i + 1] ? process.argv[i + 1] : fallback;
}

function render(inventory, { interval = '30s' } = {}) {
    const jobs = [];
    const services = inventory.services || {};
    for (const id of Object.keys(services).sort()) {
        const s = services[id];
        if (s.metrics === false) continue;
        const m = s.metrics && typeof s.metrics === 'object' ? s.metrics : {};
        const path = m.path || '/metrics';
        const targets = [];
        if (Number.isInteger(s.port)) targets.push({ port: s.port, process: id });
        for (const x of Array.isArray(m.extra) ? m.extra : []) {
            if (Number.isInteger(x.port) && /^[a-z][a-z0-9-]*$/.test(String(x.name || ''))) targets.push({ port: x.port, process: `${id}-${x.name}` });
        }
        if (!targets.length) continue;
        jobs.push({ id, path, targets });
    }
    const lines = [
        '# Generated by OpenVibe.Host scripts/prometheus-config.js from the host inventory. Do not edit by hand.',
        'global:',
        `  scrape_interval: ${interval}`,
        '  scrape_timeout: 10s',
        'scrape_configs:',
        '  - job_name: node',
        '    static_configs:',
        "      - targets: ['127.0.0.1:9100']",
    ];
    for (const j of jobs) {
        lines.push(`  - job_name: ${j.id}`, `    metrics_path: ${j.path}`, '    static_configs:');
        for (const t of j.targets) lines.push(`      - targets: ['127.0.0.1:${t.port}']`, '        labels:', `          service: ${j.id}`, `          process: ${t.process}`);
    }
    return `${lines.join('\n')}\n`;
}

if (require.main === module) {
    const inv = JSON.parse(fs.readFileSync(arg('inventory', process.env.OVHOST_INVENTORY || '/etc/openvibe/host.json'), 'utf8'));
    process.stdout.write(render(inv, { interval: arg('interval', '30s') }));
}

module.exports = { render };
